### ISSUE TITLE
Build instructions/scripts

### ISSUE THREAD

**Issue by rsuchecki** [TravisWheelerLab/Mirage#19]
I would like to try out Mirage but it seems that the build/install instructions and scripts may need updating. I should be able to setup the dependencies and may be able to put files in the right places manually but it may be worth fixing.

**Comment by anord925** [comment]
Sorry about that -- we've just been implementing some pretty big changes to how installation works, and it looks like I've been asleep at the wheel w.r.t. the setup script.  I'll post a second response once it's re-worked (shouldn't be more than a couple hours!).

**Comment by anord925** [comment]
Hi Rad, it should be working according to the original install instructions again! (just run SETUP.pl and then you're good to go)  Let me know if you run into any other issues and I'll get back to you ASAP

**Comment by rsuchecki** [comment]
Fantastic - thanks for the quick response & the fix Alex!

I'll be back with more complaints 😁

**Comment by traviswheeler** [comment]
complaints are the sincerest form of flattery
